export const ADD_TO_CART = "ADD_TO_CART";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_CART_ITEM = "FETCH_CART_ITEM";
export const CLICK_MORE_QUANTITY = "CLICK_MORE_QUANTITY";
export const CLICK_LESS_QUANTITY = "CLICK_LESS_QUANTITY";
export const CLICK_REMOVE_ITEM = "CLICK_REMOVE_ITEM";

